Unescape JSON values to avoid malformed URIs
When used against LocatorHub (our version was 10.2.2), the LocatorHub responses contain escaped forward slashes (`\/`), which in turn causes the requests to end up with the following exception: 

    UriFormatException: Invalid URI: The hostname could not be parsed.